name: 打包Docker镜像

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    paths:
      - 'VERSION'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Load VERSION
        run: echo "VERSION=$(cat VERSION)" >> $GITHUB_ENV  

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Waiting for compilation
        run: sleep 180s  

      - name: 构建镜像
        uses: docker/build-push-action@v5
        with:
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: | 
            wjqserver/ip:${{ env.VERSION }}
            wjqserver/ip:latest
