name: Build

on:
  workflow_dispatch:
  push:
    tags:
      - '([0-9]{2}w[0-9]{2}[a-zA-Z]?)'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.22
      - name: Build
        run: go build -o ip ./main.go
      - name: Package
        run: sudo tar -czvf ip.tar.gz ./ip # 将可执行文件打包为 tar.gz
      - name: Upload to GitHub Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ip
          path: ./ip.tar.gz
      - name: 上传至Release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          name: ${{ github.event.release.name }}
          artifacts: ./ip.tar.gz, ./ip
          body: ${{ github.event.release.body }}
          token: ${{ secrets.REPO_TOKEN }}
          tag: ${{ github.event.release.tag_name }}
          allowUpdates: true
        env:
          export PATH: $PATH:/usr/local/go/bin