name: Build IP

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 导入仓库
        uses: actions/checkout@v3
      - name: 加载版本号
        run: echo "VERSION=$(cat VERSION)" >> $GITHUB_ENV
      - name: Go环境部署
        uses: actions/setup-go@v3
        with:
          go-version: 1.23.0
      - name: 编译
        run: go build -o ip ./main.go
      - name: 打包
        run: sudo tar -czvf ip.tar.gz ./ip # 将可执行文件打包为 tar.gz
      - name: 上传至Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ip
          path: ./ip.tar.gz
      - name: 上传至Release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          name: ${{ env.VERSION }}
          artifacts: ./ip.tar.gz, ./ip
          token: ${{ secrets.REPO_TOKEN }}
          tag: ${{ env.VERSION }}
          allowUpdates: true
        env:
          export PATH: $PATH:/usr/local/go/bin
